-- +goose Up
CREATE TABLE v2_withdrawal_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id BIGINT NOT NULL,
    shop_id BIGINT NOT NULL,
    amount DOUBLE PRECISION NOT NULL,
    user_id BIGINT NOT NULL,
    at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX idx_v2_withdrawal_logs_team_shop
    ON v2_withdrawal_logs (team_id, shop_id);

CREATE INDEX idx_v2_withdrawal_logs_at
    ON v2_withdrawal_logs (at);

-- +goose Down
DROP INDEX IF EXISTS idx_v2_withdrawal_logs_at;
DROP INDEX IF EXISTS idx_v2_withdrawal_logs_team_shop;
DROP TABLE IF EXISTS v2_withdrawal_logs;
