// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/pdcgo/shared/configs"
	"github.com/pdcgo/shared/custom_connect"
	"github.com/pdcgo/withdrawal_service"
	withdrawal_service2 "github.com/pdcgo/withdrawal_service/v2"
	"net/http"
)

// Injectors from wire.go:

func InitializeApp() (*App, error) {
	serveMux := http.NewServeMux()
	appConfig, err := configs.NewProductionConfig()
	if err != nil {
		return nil, err
	}
	db, err := NewDatabase(appConfig)
	if err != nil {
		return nil, err
	}
	cache, err := NewCache()
	if err != nil {
		return nil, err
	}
	authorization := NewAuthorization(appConfig, db, cache)
	defaultInterceptor, err := custom_connect.NewDefaultInterceptor()
	if err != nil {
		return nil, err
	}
	publishProvider := NewGcpPublisher()
	registerHandler := withdrawal_service.NewRegister(db, authorization, serveMux, defaultInterceptor, publishProvider)
	bucketConfig := NewBucketConfig()
	client, err := NewStorageClient()
	if err != nil {
		return nil, err
	}
	withdrawalStorage := withdrawal_service2.NewWdStorage(client, bucketConfig)
	defaultClientInterceptor, err := custom_connect.NewDefaultClientInterceptor()
	if err != nil {
		return nil, err
	}
	withdrawalServiceClient := NewWithdrawalClientV1(appConfig, defaultClientInterceptor)
	revenueServiceClient := NewRevenueClient(appConfig, defaultClientInterceptor)
	orderServiceClient := NewOrderClient(appConfig, defaultClientInterceptor)
	adsExpenseServiceClient := NewAdsExpenseServiceClient(appConfig, defaultClientInterceptor)
	withdrawal_serviceRegisterHandler := withdrawal_service2.NewRegister(bucketConfig, db, authorization, serveMux, client, withdrawalStorage, withdrawalServiceClient, revenueServiceClient, orderServiceClient, adsExpenseServiceClient, defaultInterceptor)
	accountReportServiceClient := NewAccountReportServiceClient(appConfig, defaultClientInterceptor)
	app := NewApp(serveMux, registerHandler, withdrawal_serviceRegisterHandler, accountReportServiceClient)
	return app, nil
}
