// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package datasource_shopee

import (
	"context"
	"io"
)

// Injectors from wire.go:

func CreateValidWithdrawalHandler(ctx context.Context, files []io.ReadCloser) ([]*ShopeeWdSet, error) {
	invoItemDataFrame, err := NewDataframe(ctx, files)
	if err != nil {
		return nil, err
	}
	v, err := NewValidWithdrawal(invoItemDataFrame)
	if err != nil {
		return nil, err
	}
	return v, nil
}
